resolver:
  url: https://raw.githubusercontent.com/commercialhaskell/stackage-snapshots/master/lts/16/27.yaml

packages:
- .

extra-deps:
- cpython-3.5.0@sha256:a2f8ca273062063bee1e5a8f80607c69bd51eda665e5c4e24bee6085faa52db6,2588
